const actionType = {
  LOGIN: "LOGIN",
  RESGISTER_SUCCESS: "RESGISTER_SUCCESS",
  RESGISTER_FAIL: "RESGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGINR_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  GET_CATEGORY: "GET_CATEGORY",
  GET_PRICE: "GET_PRICE",
  GET_AREA: "GET_AREA",
  GET_POST: " GET_POST",
  GET_POST_LIMIT: " GET_POST_LIMIT",
  GET_NEW_POST: " GET_NEW_POST",
  GET_PROVINCE: " GET_PROVINCE",
  GET_DISTRICTS: " GET_DISTRICTS",
  GET_WARD: " GET_WARD",

  //user
  GET_CURRENT: "GET_CURRENT",
};

export default actionType;
